keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
lists:
  - filter: 'dueDate < "${tomorrow at 6AM}" AND list != DONE +dueDate +order'
    hidden: true
    id: 0
    name: What's Due?
  - hidden: false
    ignore: false
    name: NOTE
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    ignore: true
    name: DONE
  - filter: 'completedDate > "${14 days ago}" -completed'
    hidden: false
    id: 1
    name: Recently Completed
settings:
  journalType: Single File
  journalPath: kanban
  taskPrefix: '#'
  maxLines: 6
  addNewCardsToTop: true
  newCardSyntax: HASHTAG
  appendNewCardsTo: imdone-tasks.md
  cards:
    colors:
      - color: red
        filter: allTags = "Personal"
    computed:
      date: '${(new Date()).toDateString()}'
      time: '${(new Date()).toLocaleTimeString()}'
      timestamp: '${(new Date()).toISOString()}'
      dueEmoji: !<tag:yaml.org,2002:js/function> |-
        function anonymous(
        ) {
        const due = this.totals["What's Due?"]
          let emoji = ':2nd_place_medal:'
          if (due >= 3) {
            emoji = ':fire:'
          } else if (due === 0) {
            emoji = ':rocket:'
          }
          return `<span style="font-size: 1.5em;">${emoji}</span>`
        }
      recentEmoji: !<tag:yaml.org,2002:js/function> |-
        function anonymous(
        ) {
        const recentlyCompleted = this.totals["Recently Completed"]
          let emoji = ':2nd_place_medal:'
          if (recentlyCompleted >= 3) {
            emoji = ':rocket:'
          } else if (recentlyCompleted === 0) {
            emoji = ':fire:'
          }
          return `<span style="font-size: 1.5em;">${emoji}</span>`
        }
      wipEmoji: !<tag:yaml.org,2002:js/function> |-
        function anonymous(
        ) {
        const doing = this.totals["DOING"]
          let emoji = ':2nd_place_medal:'
          if (doing >= 3) {
            emoji = ':fire:'
          } else if (doing === 0) {
            emoji = ':sleeping:'
          } else if (doing === 1) {
            emoji = ':rocket:'
          }
          return `<span style="font-size: 1.5em;">${emoji}</span>`
        }
    template: |

      <!--
      created:${(new Date()).toISOString()}
      -->
    links:
      - href: >-
          https://twitter.com/intent/tweet?text=${encodedText}%0ATweeted%20with%20@imdoneio
        icon: fa-twitter
        pack: fab
        title: Tweet this card
  doneList: DONE
  filteredLists:
    - filter: 'due < "${tomorrow at 6PM}" AND list != DONE +dueDate +order'
      name: What's Due?
    - filter: 'completedDate > "${7 days ago}" -completed'
      name: Recently Completed
  journalTemplate: null
  openIn: obsidian
  editorTheme: blackboard
  replaceSpacesWith: '-'
  theme: dark
